# Generated by Django 4.2.9 on 2024-02-12 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel1app', '0004_activities'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Activities',
        ),
    ]
